### ISSUE TITLE
The pre-training model of the page of the address of the download  was missing

### ISSUE THREAD

**Issue by tutu96177** [wirustea/Fast_Invoice#1]
Thank you very much for your wonderful code, but I want to verify it inference, but in the process of downloading the pre-training model, it was discovered that the page of the address of the download connection to baidu network disk that you gave was missing，see the link at the back for detail. Could you please share it again or transmit it to Google cloud disk?
[https://pan.baidu.com/error/404.html](url)

**Comment by wirustea** [comment]
We will re-share it in several days. Thank you for your valuable Suggestions.

**Comment by tutu96177** [comment]
> 
> 
> We will re-share it in several days. Thank you for your valuable Suggestions.

Thank you. When will it be ready?
